# Generated by Django 2.1.7 on 2019-05-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('tweet_volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=200)),
                ('tweet_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('source', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('favorite_count', models.IntegerField()),
                ('retweet_count', models.IntegerField()),
            ],
        ),
    ]
